# Le data mining vs le machine learning

- Data Mining : recherche d’information et de patterns cachés dans une base de données isolée ou en croisant plusieurs bases. C’est l’être humain qui explore et prend des décisions.
- Le data mining s’appuie sur des techniques et algorithmes issus de la statistique et de la gestion de bases de données.
- Les données exploitées ont souvent une taille considérable.


# Quelques exemples

- Prestation de service : identification des paramètres de prédisposition à la résiliation (churn)
- Marketing: identification de segments distincts de consommateurs 
- Production : identification de paramètres induisant des défaillances
- Pharmaceutique: classification de médicaments selon le profil chimique


# Le machine learning

- Machine Learning : Techniques de calcul permettant aux ordinateurs d’apprendre à exécuter des tâches en s’inspirant de patterns perçus sur des données, avec peu d’intervention humaine. Les tâches se résument souvent à de la prédiction.

![image](./images/ml1.png)
    

![image](./images/trend-ml.png)

# Les outils

![image](./images/poll-ml.png)

# Les types de machine learning

- Les algorithmes de machine learning peuvent être rassemblés dans 3 groupes principaux :
   - L'apprentissage supervisé
   - Cible (variable dépendante qualitative ou quantitative)
   - Prédicteurs (variables indépendantes)
   - Régression, arbre de decision, foret aléatoire, kNN, regression logistique, SVM…

- L'apprentissage non supervisé
    - Pas de variable dépendante, pas de modélisation
    - Classer des individus dans différents groups ou trouver des associations
    - Apriori algorithm, K-means.

- L'apprentissage par renforcement
    - Apprentissage pour prendre des décisions spécifique afin d’aboutir à un but précis
    - Markov Decision Process

# L’analyse de données et le machine learning avec Python

Le package la plus adaptée pour faire du data mining et du machine learning est la package **scikit-learn**


Ce package propose des fonctions prédéfinies pour un grand nombre de méthodes

- La classification : SVM, plus proches voisins, random forest…
- Les régressions : linéaire, ridge, Lasso…
- Le clustering : k-means…
- L’analyse de données :  ACP, DA…

Dans le cadre de cette formation, l'objectf n'est pas de décrire la théorie des méthodes mais plutôt de comprendre l'utilisation de Python pour les appliquer.

# L’apprentissage supervisé avec Scikit-Learn
Les méthodes d’apprentissage supervisé sont les méthodes actuellement les plus
utilisées en data science. Il s’agit d’essayer de prédire une variable cible et d’utiliser
différentes méthodes pour arriver à cette fin.
Nous allons illustrer ces méthodes de traitement de données avec du code et des
cas pratiques.

### Les données et leur transformation
Ce jeu de données est décrit en détail au début du chapitre 4. Pour rappel, il est composé de 3333 individus et de 18 variables. Il est stocké dans un fichier csv, nommé telecom.csv, accessible dans le répertoire Data. On le récupère en utilisant Pandas :

In [1]:
import pandas as pd
import numpy as np

In [2]:
churn=pd.read_csv("./data/telecom.csv")

In [3]:
churn.head()

State  Account Length  Area Code     Phone Int'l Plan VMail Plan  \
0    KS             128        415  382-4657         no        yes   
1    OH             107        415  371-7191         no        yes   
2    NJ             137        415  358-1921         no         no   
3    OH              84        408  375-9999        yes         no   
4    OK              75        415  330-6626        yes         no   

   VMail Message  Day Mins  Day Calls  Day Charge  ...  Eve Calls  Eve Charge  \
0             25     265.1        110       45.07  ...         99       16.78   
1             26     161.6        123       27.47  ...        103       16.62   
2              0     243.4        114       41.38  ...        110       10.30   
3              0     299.4         71       50.90  ...         88        5.26   
4              0     166.7        113       28.34  ...        122       12.61   

   Night Mins  Night Calls  Night Charge  Intl Mins  Intl Calls  Intl Charge  \
0       244.7           91         11.01       10.0           3         2.70   
1       254.4          103         11.45       13.7           3         3.70   
2       162.6          104          7.32       12.2           5         3.29   
3       196.9           89          8.86        6.6           7         1.78   
4       186.9          121          8.41       10.1           3         2.73   

   CustServ Calls  Churn?  
0               1  False.  
1               1  False.  
2               0  False.  
3               2  False.  
4               3  False.  

[5 rows x 21 columns]

## Les données

Ce jeu de données n’a pas de données manquantes et nous allons devoir effectuer
quelques transformations pour l’adapter à nos traitements. Nous voyons par exemple qu’il est composé de trois colonnes object.

Nous pouvons afficher les statistiques descriptives pour les colonnes object :

In [4]:
churn.describe(include="object").transpose()

count unique       top  freq
State       3333     51        WV   106
Phone       3333   3333  367-8156     1
Int'l Plan  3333      2        no  3010
VMail Plan  3333      2        no  2411
Churn?      3333      2    False.  2850

## Transformation des données

On voit que les données sont toutes binaires. 

Pour les variables binaires, il nous suffit de les recoder avec Scikit-Learn pour obtenir des données exploitables. Par
ailleurs, il existe une autre variable qualitative dans notre jeu de données, Area Code,
qui est numérique mais avec trois modalités :

In [5]:
churn["Area Code"].value_counts()

415    1655
510     840
408     838
Name: Area Code, dtype: int64

In [6]:
pd.get_dummies(churn["Area Code"])

408  415  510
0       0    1    0
1       0    1    0
2       0    1    0
3       1    0    0
4       0    1    0
5       0    0    1
6       0    0    1
7       0    1    0
8       1    0    0
9       0    1    0
10      0    1    0
11      0    1    0
12      1    0    0
13      0    0    1
14      0    1    0
15      0    1    0
16      1    0    0
17      0    0    1
18      0    0    1
19      0    1    0
20      0    1    0
21      1    0    0
22      0    1    0
23      0    1    0
24      0    0    1
25      0    1    0
26      1    0    0
27      1    0    0
28      0    1    0
29      0    0    1
...   ...  ...  ...
3303    0    1    0
3304    0    0    1
3305    0    1    0
3306    1    0    0
3307    1    0    0
3308    0    1    0
3309    1    0    0
3310    0    1    0
3311    0    1    0
3312    1    0    0
3313    1    0    0
3314    0    1    0
3315    0    1    0
3316    0    0    1
3317    0    1    0
3318    0    1    0
3319    0    1    0
3320    0    0    1
3321    0    1    0
3322    1    0    0
3323    0    1    0
3324    0    1    0
3325    1    0    0
3326    0    1    0
3327    0    1    0
3328    0    1    0
3329    0    1    0
3330    0    0    1
3331    0    0    1
3332    0    1    0

[3333 rows x 3 columns]

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder,Imputer

# on crée un objet qui recode les colonnes en binaire
onehot_area = OneHotEncoder(sparse=False,categories='auto')
# on stocke les paramètres de la transformation et on transforme les données
onehot_area.fit_transform(np.array(churn["Area Code"]).reshape(-1, 1))

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [8]:
# on applique la transformation sur de nouvelles données
resultat = onehot_area.transform(np.array([408,415]).reshape(-1, 1))
print(resultat)
# on effectue la transformation inverse pour récupérer le format initial
onehot_area.inverse_transform(resultat)

[[1. 0. 0.]
 [0. 1. 0.]]


array([[408],
       [415]], dtype=int64)

In [9]:
onehot_area.categories_

[array([408, 415, 510], dtype=int64)]

## La préparation des données

Nous allons utiliser le processus de traitement classique pour transformer nos
données avec Scikit-Learn. Dans ce cas, nous n’avons pas de données manquantes,
nous travaillons donc sur la transformation des variables qualitatives.

In [10]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder,Imputer
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer 

## Prédire l’attrition des clients
Lorsqu’on veut prédire une variable binaire, on devra avoir une colonne du type
binaire. On préfère généralement un codage 0/1 afin de garder un type entier simple à gérer. 

Les variables explicatives x auront été préparées de manière intelligente afin de bien appliquer nos modèles.

On crée donc x et y :

In [11]:
churn.columns

Index(['State', 'Account Length', 'Area Code', 'Phone', 'Int'l Plan',
       'VMail Plan', 'VMail Message', 'Day Mins', 'Day Calls', 'Day Charge',
       'Eve Mins', 'Eve Calls', 'Eve Charge', 'Night Mins', 'Night Calls',
       'Night Charge', 'Intl Mins', 'Intl Calls', 'Intl Charge',
       'CustServ Calls', 'Churn?'],
      dtype='object')

In [12]:
list_var_x = ['VMail Message', 'Day Mins', 'Day Calls', 'Day Charge',
       'Eve Mins', 'Eve Calls', 'Eve Charge', 'Night Mins', 'Night Calls',
       'Night Charge', 'Intl Mins', 'Intl Calls', 'Intl Charge',
       'CustServ Calls']

x = churn[list_var_x]

In [13]:
y = churn["Churn?"]

In [14]:
# on peut facilement renommer une colonne
dico_rename_col = {'Day Mins':"minutes"}
churn.rename(columns=dico_rename_col).head()

State  Account Length  Area Code     Phone Int'l Plan VMail Plan  \
0    KS             128        415  382-4657         no        yes   
1    OH             107        415  371-7191         no        yes   
2    NJ             137        415  358-1921         no         no   
3    OH              84        408  375-9999        yes         no   
4    OK              75        415  330-6626        yes         no   

   VMail Message  minutes  Day Calls  Day Charge  ...  Eve Calls  Eve Charge  \
0             25    265.1        110       45.07  ...         99       16.78   
1             26    161.6        123       27.47  ...        103       16.62   
2              0    243.4        114       41.38  ...        110       10.30   
3              0    299.4         71       50.90  ...         88        5.26   
4              0    166.7        113       28.34  ...        122       12.61   

   Night Mins  Night Calls  Night Charge  Intl Mins  Intl Calls  Intl Charge  \
0       244.7           91         11.01       10.0           3         2.70   
1       254.4          103         11.45       13.7           3         3.70   
2       162.6          104          7.32       12.2           5         3.29   
3       196.9           89          8.86        6.6           7         1.78   
4       186.9          121          8.41       10.1           3         2.73   

   CustServ Calls  Churn?  
0               1  False.  
1               1  False.  
2               0  False.  
3               2  False.  
4               3  False.  

[5 rows x 21 columns]

## Séparation des données

Pour la séparation, on utilise la fonction train_test_split() de Scikit-Learn.

Cette fonction permet de créer automatiquement autant de structures que nécessaire
à partir de nos données. 

Elle utilise une randomisation des individus et ensuite une séparation en fonction d’un paramètre du type test_size :

In [15]:
# on importe la fonction
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3,stratify= y)

Dans certains cas, il peut arriver qu’il y ait une forte disparité de distribution des
modalités entre les proportions d’acceptation et de refus. On peut vouloir faire en
sorte que les répartitions des modalités de y soient égales dans les différents échantillons,
on pourra alors utiliser une stratification. On va utiliser une stratification en
prenant y comme base pour effectuer la stratification :

In [16]:
y.value_counts(normalize=True)

False.    0.855086
True.     0.144914
Name: Churn?, dtype: float64

Ainsi les deux échantillons _train et _test ont la même distribution

In [17]:
y_test.value_counts(normalize=True)

False.    0.855
True.     0.145
Name: Churn?, dtype: float64

In [18]:
y_train.value_counts(normalize=True)

False.    0.855122
True.     0.144878
Name: Churn?, dtype: float64

## Le choix et l’ajustement de l’algorithme

Tout au long de ce Notebook, nous allons essayer d'ajouter un nouveau modèle, il s'agit du modèle GBM
```python
from sklearn.ensemble import GradientBoostingClassifier
```

In [19]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

Ensuite, on crée un objet à partir de la classe du modèle en lui fournissant les
hyperparamètres dont il a besoin :

In [20]:
modele_rf=RandomForestClassifier(n_estimators=100)
modele_knn=KNeighborsClassifier(n_neighbors=5)

Dans ce cas, on prend les hyperparamètres par défaut.

On peut ensuite ajuster notre modèle en utilisant les données :

In [21]:
modele_rf.fit(x_train,y_train)
modele_knn.fit(x_train,y_train)
pass

Une fois qu’on a estimé les paramètres du modèle, on va pouvoir extraire des
informations. De nouveaux attributs de chaque classe apparaissent, ils se terminent par le symbole underscore _ :

In [22]:
modele_rf.feature_importances_

array([0.04901733, 0.1433261 , 0.04878793, 0.15023643, 0.08234964,
       0.04068536, 0.08028005, 0.05243338, 0.04565279, 0.04992769,
       0.04673657, 0.03101876, 0.04876138, 0.13078658])

Ce qui va nous intéresse avant tout, c’est de prédire avec notre modèle. Pour cela nous allons utiliser la méthode .predict() :

In [23]:
y_predict_rf = modele_rf.predict(x_test)
y_predict_knn = modele_knn.predict(x_test)

On obtient ainsi une valeur prédite pour les éléments de notre échantillon de
validation.

## Les indicateurs pour valider un modèle
La partie validation d’un modèle d’apprentissage supervisé est extrêmement
importante. L’objectif d’un modèle d’apprentissage supervisé est de prédire une
valeur la plus proche possible de la réalité. Nous différencions trois types d’indices
en fonction du type de variable cible. Tous les indicateurs de qualité du modèle sont
stockés dans le module *metrics* de Scikit-Learn.

## Le pourcentage de bien classés
Il s’agit de l’indicateur le plus connu. On le nomme accuracy. Il est calculé à partir du rapport entre le nombre d’individus bien classés et le nombre total d’individus dans l’échantillon.

In [24]:
from sklearn.metrics import accuracy_score, recall_score

accuracy_modele_rf = accuracy_score(y_test,y_predict_rf)
accuracy_modele_knn = accuracy_score(y_test,y_predict_knn)
print("Pourcentage de bien classés pour le modèle RF : %.3f" %(accuracy_modele_rf))
print("Pourcentage de bien classés pour le modèle kNN :%.3f" %(accuracy_modele_knn))

#recall_modele_rf=recall_score(y_test,y_predict_rf)
#recall_modele_knn=recall_score(y_test,y_predict_knn)
#print("Rappel pour le modèle RF : %.3f" %(recall_modele_rf))
#print("Rappel pour le modèle kNN :%.3f" %(recall_modele_knn))

Pourcentage de bien classés pour le modèle RF : 0.921
Pourcentage de bien classés pour le modèle kNN :0.891


## La matrice de confusion
Il s’agit d’un autre indicateur important pour juger de la qualité d’un modèle, il n’est pas défini par une seule valeur mais par une matrice dans laquelle on peut lire le croisement entre les valeurs observées et les valeurs prédites à partir du modèle. 

Pour calculer cette matrice, on pourra utiliser :

In [25]:
from sklearn.metrics import confusion_matrix
confusion_matrix_rf=confusion_matrix(y_test,y_predict_rf)
confusion_matrix_knn=confusion_matrix(y_test,y_predict_knn)
print("Matrice de confusion pour le modèle RF :",
confusion_matrix_rf, sep="\n")
print("Matrice de confusion pour le modèle kNN :",
confusion_matrix_knn, sep="\n")

Matrice de confusion pour le modèle RF :
[[847   8]
 [ 71  74]]
Matrice de confusion pour le modèle kNN :
[[841  14]
 [ 95  50]]


## Le rappel (recall), la précision et le f1-score

Scikit-Learn possède des fonctions pour chacun de ces indicateurs, mais il peut
être intéressant d’utiliser une autre fonction qui les affiche pour chaque classe :

tp / (tp + fn)

In [26]:
from sklearn.metrics import classification_report
print("Rapport pour le modèle RF :",
      classification_report(y_test,y_predict_rf) ,sep="\n")

Rapport pour le modèle RF :
              precision    recall  f1-score   support

      False.       0.92      0.99      0.96       855
       True.       0.90      0.51      0.65       145

    accuracy                           0.92      1000
   macro avg       0.91      0.75      0.80      1000
weighted avg       0.92      0.92      0.91      1000



In [27]:
print("Rapport pour le modèle kNN :",
      classification_report(y_test,y_predict_knn) ,sep="\n")

Rapport pour le modèle kNN :
              precision    recall  f1-score   support

      False.       0.90      0.98      0.94       855
       True.       0.78      0.34      0.48       145

    accuracy                           0.89      1000
   macro avg       0.84      0.66      0.71      1000
weighted avg       0.88      0.89      0.87      1000



In [28]:
# ajouter le 3ème modèle

## L’aire sous la courbe ROC
La courbe ROC est un indicateur important mais on préfère souvent une valeur plutôt
qu’une courbe afin de comparer nos modèles. Pour cela, on utilise l’aire sous la courbe
ROC (AUC). Cette aire est calculée directement à partir de la courbe ROC. Ainsi, un
modèle aléatoire aura une AUC de 0.5 et un modèle parfait aura une AUC de 1.

In [29]:
from sklearn.metrics import roc_auc_score
auc_modele_rf=roc_auc_score(y_test, modele_rf.predict_proba(x_test)[:,1])
auc_modele_knn=roc_auc_score(y_test,modele_knn.predict_proba(x_test)[:,1])

print("Aire sous la courbe ROC pour le modèle RF :" ,auc_modele_rf)
print("Aire sous la courbe ROC pour le modèle kNN :" ,auc_modele_knn)

Aire sous la courbe ROC pour le modèle RF : 0.8706513409961685
Aire sous la courbe ROC pour le modèle kNN : 0.6866102036700947


## La validation croisée
Jusqu’ici nous avons utilisé des indicateurs basés sur une seule occurrence de test. Ceci veut dire qu’on ne teste notre modèle que sur un seul échantillon.

Une approche alternative souvent utilisée est la validation croisée. Celle-ci est en fait basée sur la répétition de l’estimation et de la validation sur des données différentes.

Pour obtenir ce cv-score, on utilise :

In [30]:
from sklearn.model_selection import cross_val_score

scores_rf = cross_val_score(modele_rf, x_train, y_train, cv=5, scoring='roc_auc')
scores_knn = cross_val_score(modele_knn, x_train, y_train, cv=5, scoring='roc_auc')

print("AUC pour RF : %.3f (+/- %.3f)"% (scores_rf.mean(), scores_rf.std() * 2))
print("AUC pour kNN : %.3f (+/- %.3f)"% (scores_knn.mean(),scores_knn.std() * 2))

AUC pour RF : 0.861 (+/- 0.064)
AUC pour kNN : 0.680 (+/- 0.115)


## L’ajustement des hyperparamètres d’un modèle

L’une des tâches du data scientist est de trouver le meilleur modèle possible. La
plupart des modèles de machine learning ont des hyperparamètres. Il s’agit de paramètres
du modèle qui sont définis en amont de l’ajustement.

Scikit-Learn propose une classe GridSearchCV permettant d’implémenter cette
recherche d’hyperparamètres :

In [31]:
from sklearn.model_selection import GridSearchCV

On va donc devoir définir les hyperparamètres que l’on souhaite tester. Pour cela,
on utilisera un dictionnaire d’hyperparamètres, par exemple :

In [32]:
dico_param = {"max_depth":[3,5,7,10], "n_estimators":[10,20,50,100]}

On va encore utiliser l’accuracy pour valider notre modèle. Finalement, nous allons
utiliser une validation croisée à cinq groupes pour valider les résultats.
Le nouvel objet est le suivant :

In [33]:
recherche_hyper = GridSearchCV(RandomForestClassifier(), 
                               dico_param, 
                               scoring="accuracy",cv=5)

Une fois qu’on a créé cet objet, on peut lui joindre les données afin d’estimer les
meilleurs paramètres du modèle.

Cette étape peut être très longue.

In [34]:
recherche_hyper.fit(x_train, y_train)

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators='warn', n_jobs=None,
                                              oob_score=False,
                                              random_state=None, verbose=0,
                                              warm_start=False),
             iid

In [35]:
print(recherche_hyper.best_params_)

{'max_depth': 10, 'n_estimators': 100}


In [36]:
print(recherche_hyper.best_score_)

0.9164166309472782


In [37]:
pd.DataFrame(recherche_hyper.cv_results_)

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.032714      0.001183         0.004787        0.000398   
1        0.057646      0.001616         0.006582        0.000490   
2        0.131566      0.006181         0.011902        0.001863   
3        0.262455      0.006272         0.018752        0.006262   
4        0.039945      0.008537         0.003130        0.006261   
5        0.071858      0.007640         0.009373        0.007653   
6        0.173839      0.004869         0.010837        0.005737   
7        0.339024      0.007298         0.020277        0.005752   
8        0.046857      0.000012         0.006255        0.007661   
9        0.090468      0.001551         0.006982        0.000001   
10       0.215778      0.004550         0.012367        0.000490   
11       0.422835      0.004830         0.020168        0.001537   
12       0.056862      0.000621         0.005570        0.000495   
13       0.106914      0.000738         0.007580        0.000488   
14       0.263696      0.010008         0.012942        0.000019   
15       0.512812      0.004108         0.020005        0.003578   

   param_max_depth param_n_estimators                                  params  \
0                3                 10    {'max_depth': 3, 'n_estimators': 10}   
1                3                 20    {'max_depth': 3, 'n_estimators': 20}   
2                3                 50    {'max_depth': 3, 'n_estimators': 50}   
3                3                100   {'max_depth': 3, 'n_estimators': 100}   
4                5                 10    {'max_depth': 5, 'n_estimators': 10}   
5                5                 20    {'max_depth': 5, 'n_estimators': 20}   
6                5                 50    {'max_depth': 5, 'n_estimators': 50}   
7                5                100   {'max_depth': 5, 'n_estimators': 100}   
8                7                 10    {'max_depth': 7, 'n_estimators': 10}   
9                7                 20    {'max_depth': 7, 'n_estimators': 20}   
10               7                 50    {'max_depth': 7, 'n_estimators': 50}   
11               7                100   {'max_depth': 7, 'n_estimators': 100}   
12              10                 10   {'max_depth': 10, 'n_estimators': 10}   
13              10                 20   {'max_depth': 10, 'n_estimators': 20}   
14              10                 50   {'max_depth': 10, 'n_estimators': 50}   
15              10                100  {'max_depth': 10, 'n_estimators': 100}   

    split0_test_score  split1_test_score  split2_test_score  \
0            0.869379           0.856531           0.873662   
1            0.854390           0.871520           0.873662   
2            0.869379           0.871520           0.873662   
3            0.875803           0.873662           0.875803   
4            0.892934           0.873662           0.871520   
5            0.916488           0.897216           0.899358   
6            0.890792           0.875803           0.897216   
7            0.886510           0.886510           0.892934   
8            0.916488           0.905782           0.895075   
9            0.903640           0.899358           0.890792   
10           0.914347           0.897216           0.903640   
11           0.918630           0.892934           0.901499   
12           0.910064           0.892934           0.910064   
13           0.916488           0.899358           0.897216   
14           0.914347           0.897216           0.914347   
15           0.918630           0.903640           0.910064   

    split3_test_score  split4_test_score  mean_test_score  std_test_score  \
0            0.896996           0.873391         0.873982        0.013080   
1            0.896996           0.858369         0.870982        0.014952   
2            0.864807           0.875536         0.870982        0.003711   
3            0.886266           0.869099         0.876125        0.005627   
4           

## La construction d’un pipeline de traitement

Bien souvent vous allez être amené à enchaîner des traitements sur des données.
On peut bien sûr développer son code de manière à suivre les étapes une à une mais il est souvent plus intéressant de créer des suites de traitements automatisées avec Scikit-Learn. 

Ces suites de traitements sont appelées pipeline. Ils simplifieront votre code et permettront de passer en production simplement.

Ainsi, on va pouvoir faire une analyse en composantes principales suivies d’un
algorithme de plus proches voisins directement dans un pipeline :

In [38]:
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.decomposition import PCA

In [39]:
acp=PCA(n_components=8)
knn=KNeighborsClassifier()
rf=RandomForestClassifier()

pipe=Pipeline(steps=[("acp",acp),("knn",knn)])
pipe2=Pipeline(steps=[("acp",acp),("rf",rf)])

pipe.fit(x_train, y_train)

pipe2.fit(x_train, y_train)
pass

C:\Users\s4d-asus-14\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [40]:
pipe2.predict(x_test)

array(['False.', 'False.', 'False.', 'False.', 'True.', 'False.',
       'False.', 'False.', 'False.', 'False.', 'False.', 'False.',
       'False.', 'False.', 'False.', 'False.', 'False.', 'False.',
       'False.', 'True.', 'False.', 'False.', 'False.', 'False.',
       'False.', 'False.', 'False.', 'False.', 'False.', 'False.',
       'False.', 'False.', 'False.', 'False.', 'False.', 'False.',
       'False.', 'True.', 'False.', 'False.', 'False.', 'False.',
       'False.', 'False.', 'False.', 'False.', 'False.', 'False.',
       'False.', 'False.', 'False.', 'False.', 'False.', 'False.',
       'False.', 'False.', 'False.', 'False.', 'False.', 'False.',
       'False.', 'False.', 'False.', 'False.', 'False.', 'False.',
       'False.', 'False.', 'False.', 'True.', 'False.', 'False.',
       'False.', 'False.', 'False.', 'False.', 'False.', 'False.',
       'False.', 'True.', 'False.', 'False.', 'False.', 'False.',
       'False.', 'True.', 'False.', 'False.', 'False.', 'False.',
 

In [41]:
x_train_comp = acp.fit_transform(x_train)
rf.fit(x_train_comp, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [42]:
x_test_comp = acp.transform(x_test)
rf.predict(x_test_comp)

array(['False.', 'False.', 'False.', 'False.', 'False.', 'False.',
       'False.', 'False.', 'False.', 'False.', 'False.', 'False.',
       'False.', 'False.', 'False.', 'False.', 'False.', 'False.',
       'False.', 'True.', 'False.', 'False.', 'False.', 'False.',
       'False.', 'False.', 'False.', 'False.', 'False.', 'False.',
       'False.', 'False.', 'False.', 'False.', 'False.', 'False.',
       'False.', 'False.', 'False.', 'False.', 'False.', 'False.',
       'False.', 'False.', 'False.', 'False.', 'False.', 'False.',
       'False.', 'False.', 'False.', 'False.', 'False.', 'False.',
       'False.', 'False.', 'False.', 'False.', 'False.', 'False.',
       'False.', 'False.', 'False.', 'False.', 'False.', 'False.',
       'False.', 'False.', 'False.', 'True.', 'False.', 'False.',
       'False.', 'False.', 'False.', 'False.', 'False.', 'False.',
       'False.', 'True.', 'False.', 'False.', 'False.', 'False.',
       'False.', 'True.', 'False.', 'False.', 'False.', 'False.',

In [43]:
pipe2

Pipeline(memory=None,
         steps=[('acp',
                 PCA(copy=True, iterated_power='auto', n_components=8,
                     random_state=None, svd_solver='auto', tol=0.0,
                     whiten=False)),
                ('rf',
                 RandomForestClassifier(bootstrap=True, class_weight=None,
                                        criterion='gini', max_depth=None,
                                        max_features='auto',
                                        max_leaf_nodes=None,
                                        min_impurity_decrease=0.0,
                                        min_impurity_split=None,
                                        min_samples_leaf=1, min_samples_split=2,
                                        min_weight_fraction_leaf=0.0,
                                        n_estimators=10, n_jobs=None,
                                        oob_score=False, random_state=None,
                                        verbose=0, warm

On a ainsi enchaîné deux traitements. Si on cherche des sorties liées à chacune
des étapes, on pourra le faire simplement. Par exemple, si l’objectif est d’extraire la part de variances expliquées par les composantes de l’analyse en composantes principales, on fera :

In [44]:
pipe.named_steps["acp"].explained_variance_ratio_

array([0.32613334, 0.26603217, 0.26354245, 0.04285955, 0.04059586,
       0.03959923, 0.01956745, 0.00085682])

## Trouver la meilleure combinaison d’hyperparamètres dans un pipeline

Essayons de trouver la meilleure combinaison d’hyperparamètres dans un pipeline.
Dans le cadre de cet exemple, nous utiliserons les SVM (support vector machines,
également appelés séparateurs à vaste marge ou machines à vecteurs de support).
Ce sont des méthodes assez complexes dans leur principe mais simples dans leur
mise en oeuvre.

Les hyperparamètres d’un modèle de SVM sont assez nombreux. Les plus importants
étant le noyau choisi (linéaire, polynomial, sigmoïd, RBF…), les paramètres de
ces noyaux (le degré pour le cas polynomiale, gamma…) et le C pour la marge floue.

Dans notre exemple, on utilisera la fonction make_pipeline qui est équivalente
à la classe précédente avec quelques simplifications :

In [45]:
from sklearn.pipeline import make_pipeline
from sklearn.svm import SVC
from sklearn.decomposition import PCA
from sklearn.model_selection import GridSearchCV

# construction du pipeline basé sur deux approches
mon_pipe=make_pipeline(PCA(), SVC(probability=True))

# construction du dictionnaire des paramètres
# (attention utilisation de __)
param_grid = dict(pca__n_components=[5, 10, x_train.shape[1]],
                  svc__C= [1, 10, 100, 1000],
                  svc__kernel= ['sigmoid', 'rbf'],
                  svc__gamma= [0.001, 0.0001])

# on construit l’objet GridSearch et on estime les hyper-paramètres
# par validation croisée
grid_search_mon_pipe = GridSearchCV(mon_pipe, param_grid = param_grid, scoring = "roc_auc", cv = 4)

In [46]:
grid_search_mon_pipe.fit(x_train,y_train)
pass

In [47]:
# la meilleure combinaisons de paramètres est :
grid_search_mon_pipe.best_params_

{'pca__n_components': 14,
 'svc__C': 10,
 'svc__gamma': 0.0001,
 'svc__kernel': 'rbf'}

In [48]:
grid_search_mon_pipe.best_score_

0.7891426063382316

Les meilleurs hyperparamètres obtenus en utilisant l’aire sous la courbe ROC sont
la combinaison C = 10, gamma = 0.0001, un noyau RBF pour les SVM et dix composantes
pour notre analyse en composantes principales.

Dans ce code, on définit les hyperparamètres associés à une méthode du pipeline
avec un double underscore : __.

L’utilisation des pipelines de Scikit-Learn va devenir rapidement une étape cruciale
de vos développements en Python.

## Passer en production votre modèle d’apprentissage supervisé

### Persistance de modèle avec Scikit-Learn

Python possède plusieurs outils pour la persistance d’objets, c’est-à-dire pour stocker
des objets dans des fichiers. Les objets de Scikit-Learn sont aussi dans cette
situation. On utilise un format pickle qui aura l’extension .pkl.

Par exemple, si nous voulons sauvegarder le dernier pipeline de traitement, nous
allons utiliser :

In [49]:
from sklearn.externals import joblib
joblib.dump(pipe2, './data/modele_pipe2.pkl')

C:\Users\s4d-asus-14\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


['./data/modele_pipe2.pkl']

Une fois ce modèle stocké, on peut très bien le réutiliser dans un autre cadre. Si
nous créons un nouveau notebook, nous allons utiliser :



In [51]:
from sklearn.externals import joblib
#grid_search_mon_pipe = joblib.load('./data/modele_grid_pipe.pkl')

On peut ensuite appliquer le modèle avec tous les paramètres qui ont été appris :


```python
grid_search_mon_pipe.predict(x_test)
```

L’utilisation d’un fichier Pickle dans un notebook est une technique assez simple et courante.